package com.ht.entities;
// Generated Dec 20, 2020, 10:04:20 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Logo generated by hbm2java
 */
@Entity
@Table(name = "logo", catalog = "book_dacnpm")
public class Logo implements java.io.Serializable {

	private int idLogo;
	private String img;

	public Logo() {
	}

	public Logo(int idLogo) {
		this.idLogo = idLogo;
	}

	public Logo(int idLogo, String img) {
		this.idLogo = idLogo;
		this.img = img;
	}

	@Id

	@Column(name = "idLogo", unique = true, nullable = false)
	public int getIdLogo() {
		return this.idLogo;
	}

	public void setIdLogo(int idLogo) {
		this.idLogo = idLogo;
	}

	@Column(name = "img")
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

}
