package com.ht.entities;
// Generated Dec 20, 2020, 10:04:20 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotBlank;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name = "sach", catalog = "book_dacnpm")
public class Sach implements java.io.Serializable {

	private long maSach;
	private long theloaisach;
	private String tenSach;
	private long gia;
	private Integer soLuong;
	private String tenTacGia;
	private String hinhAnh;
	private String moTa;
	private int khuyenMai;
	private Date ngayXuatBan;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	private List<ReceiptItem> listReceiptItem;
//	private Set<Comment> comments = new HashSet<Comment>(0);
//	private Set<Billcontainsach> billcontainsaches = new HashSet<Billcontainsach>(0);
//	private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);

	public Sach() {
	}

	public Sach(long gia, String moTa, int khuyenMai) {
		this.gia = gia;
		this.moTa = moTa;
		this.khuyenMai = khuyenMai;
	}

	public Sach(long theloaisach, String tenSach, long gia, Integer soLuong, String tenTacGia, String hinhAnh,
			String moTa, int khuyenMai, Date ngayXuatBan) {
		this.theloaisach = theloaisach;
		this.tenSach = tenSach;
		this.gia = gia;
		this.soLuong = soLuong;
		this.tenTacGia = tenTacGia;
		this.hinhAnh = hinhAnh;
		this.moTa = moTa;
		this.khuyenMai = khuyenMai;
		this.ngayXuatBan = ngayXuatBan;
//		this.comments = comments;
//		this.billcontainsaches = billcontainsaches;
//		this.wishlists = wishlists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "maSach", unique = true, nullable = false)
	public long getMaSach() {
		return this.maSach;
	}

	public void setMaSach(long maSach) {
		this.maSach = maSach;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "loaiSach")
//	public Theloaisach loaiSach;

	@Column(name = "loaiSach")
	public long getTheloaisach() {
		return this.theloaisach;
	}

	public void setTheloaisach(long theloaisach) {
		this.theloaisach = theloaisach;
	}

	@NotBlank(message = "must not be null")
	@Column(name = "tenSach")
	public String getTenSach() {
		return this.tenSach;
	}

	public void setTenSach(String tenSach) {
		this.tenSach = tenSach;
	}

	@Column(name = "gia", nullable = false, precision = 11, scale = 0)
	public long getGia() {
		return this.gia;
	}

	public void setGia(long gia) {
		this.gia = gia;
	}

	@Column(name = "soLuong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@NotBlank(message = "must not be null")
	@Column(name = "tenTacGia")
	public String getTenTacGia() {
		return this.tenTacGia;
	}

	public void setTenTacGia(String tenTacGia) {
		this.tenTacGia = tenTacGia;
	}

//	@NotBlank(message = "must not be null")
	@Column(name = "hinhAnh")
	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@NotBlank(message = "must not be null")
	@Column(name = "moTa", nullable = false)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@Column(name = "khuyenMai", nullable = false)
	public int getKhuyenMai() {
		return this.khuyenMai;
	}

	public void setKhuyenMai(int khuyenMai) {
		this.khuyenMai = khuyenMai;
	}

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Column(name = "ngayXuatBan", length = 10)
	public Date getNgayXuatBan() {
		return this.ngayXuatBan;
	}

	public void setNgayXuatBan(Date ngayXuatBan) {
		this.ngayXuatBan = ngayXuatBan;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sach")
//	public Set<Comment> getComments() {
//		return this.comments;
//	}
//
//	public void setComments(Set<Comment> comments) {
//		this.comments = comments;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sach")
//	public Set<Billcontainsach> getBillcontainsaches() {
//		return this.billcontainsaches;
//	}
//
//	public void setBillcontainsaches(Set<Billcontainsach> billcontainsaches) {
//		this.billcontainsaches = billcontainsaches;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sach")
//	public Set<Wishlist> getWishlists() {
//		return this.wishlists;
//	}
//
//	public void setWishlists(Set<Wishlist> wishlists) {
//		this.wishlists = wishlists;
//	}

}
