package com.ht.entities;
// Generated Dec 20, 2020, 10:04:20 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theloaisach generated by hbm2java
 */
@Entity
@Table(name = "theloaisach", catalog = "book_dacnpm")
@NamedQueries({ @NamedQuery(name = "Category.findAll", query = "Select c from Theloaisach c") })
public class Theloaisach implements java.io.Serializable {

	private long maTheLoai;
	private String tenTheLoai;

	private Set<Sach> saches = new HashSet<Sach>(0);
	private Set<Sach> saches_1 = new HashSet<Sach>(0);

	public Theloaisach() {
	}

	public Theloaisach(String tenTheLoai, Set<Sach> saches, Set<Sach> saches_1) {
		this.tenTheLoai = tenTheLoai;
		this.saches = saches;
		this.saches_1 = saches_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "maTheLoai", unique = true, nullable = false)
	public long getMaTheLoai() {
		return this.maTheLoai;
	}

	public void setMaTheLoai(long maTheLoai) {
		this.maTheLoai = maTheLoai;
	}

	@Column(name = "tenTheLoai")
	public String getTenTheLoai() {
		return this.tenTheLoai;
	}

	public void setTenTheLoai(String tenTheLoai) {
		this.tenTheLoai = tenTheLoai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theloaisach")
	public Set<Sach> getSaches() {
		return this.saches;
	}

//	@OneToMany(targetEntity = Sach.class, cascade = CascadeType.ALL)
//	@JoinColumn(name = "", referencedColumnName = "")
//	private List<Sach> sach;

	public void setSaches(Set<Sach> saches) {
		this.saches = saches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theloaisach")
	public Set<Sach> getSaches_1() {
		return this.saches_1;
	}

	public void setSaches_1(Set<Sach> saches_1) {
		this.saches_1 = saches_1;
	}

}
