package com.ht.entities;
// Generated Dec 20, 2020, 10:04:20 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tinhtrangbill generated by hbm2java
 */
@Entity
@Table(name = "tinhtrangbill", catalog = "book_dacnpm")
public class Tinhtrangbill implements java.io.Serializable {

	private int idTinhTrang;
	private String kieuTinhTrang;
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<Bill> bills_1 = new HashSet<Bill>(0);

	public Tinhtrangbill() {
	}

	public Tinhtrangbill(int idTinhTrang) {
		this.idTinhTrang = idTinhTrang;
	}

	public Tinhtrangbill(int idTinhTrang, String kieuTinhTrang, Set<Bill> bills, Set<Bill> bills_1) {
		this.idTinhTrang = idTinhTrang;
		this.kieuTinhTrang = kieuTinhTrang;
		this.bills = bills;
		this.bills_1 = bills_1;
	}

	@Id

	@Column(name = "idTinhTrang", unique = true, nullable = false)
	public int getIdTinhTrang() {
		return this.idTinhTrang;
	}

	public void setIdTinhTrang(int idTinhTrang) {
		this.idTinhTrang = idTinhTrang;
	}

	@Column(name = "kieuTinhTrang")
	public String getKieuTinhTrang() {
		return this.kieuTinhTrang;
	}

	public void setKieuTinhTrang(String kieuTinhTrang) {
		this.kieuTinhTrang = kieuTinhTrang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tinhtrangbill")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tinhtrangbill")
	public Set<Bill> getBills_1() {
		return this.bills_1;
	}

	public void setBills_1(Set<Bill> bills_1) {
		this.bills_1 = bills_1;
	}

}
